<?php

/**
 * Implements hook_theme()
 */
function link_to_paragraph_theme() {
  return [

    'link_to_paragraphs' => [
      'variables' => [
        'title' => '',
        'paragraphs' => [
          [
            'id' => '',
            'value' => '',
          ],
        ],
      ],
    ],

  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function link_to_paragraph_preprocess_paragraph(&$variables) {
  $variables['attributes']['id'] = 'paragraph-' . $variables['paragraph']->id();
}
